### PR TITLE
Add comment user mentions

### LINKED ISSUE #100: Add comment user mentions
We need to do the same as in #73 but for comments.

### PR DESCRIPTION
**Pull request by joshsmith**
Closes #100 

We need to add:
- [x] Spec for GenerateUserMentionsForComment
- [x] GenerateUserMentionsForComment methods
- [x] Model specs for comment
- [x] Same methods in model as in Post
- [x] Model specs for comment user mention
- [x] Same methods in model as in PostUserMention
- [x] Serializer specs for comment serializer
- [x] Comment serializer
- [x] Request specs for comment
- [x] Ensure includes are working as expected

### CODE REVIEW

**Comment by joshsmith** [comment]
You'll notice I serialized the comments directly on the post.

I'm not sure we should be including all this crap in the `index`. Seems like overkill. But definitely on the non-index routes.

**Comment by begedin** [comment]
:+1: Looks good to me

**Comment by begedin** [comment]
Also, I agree with not including most of the stuff on the index. We should start splitting up our serializers.

**Comment by joshsmith** [comment]
@begedin add an issue(s)?

**Comment by begedin** [comment]
Created issue for serializer - #106

**Pull request merged**
