### PR TITLE
Fix authenticated user serializer

### PR DESCRIPTION
**Pull request by joshsmith**
This adds `has_many` relationships missing from the authenticated user.

### CODE REVIEW

**Comment by begedin** [comment]
Changes look good, but looking at this right now, is there much of a point to keep `user_serializer` and  `authenticated_user_serializer`, especially considering how Ember behaves.

The differences are that `user_serializer` has `facebook_id` and `facebook_access_token`, while `authenticated_user_serializer` does not.

**Comment by joshsmith** [comment]
I think it's a good idea to keep it separate, because we don't want some of those things exposed in the general case. The gap may widen as time goes on, too.

**Comment by begedin** [comment]
I understand and generally, I think this is good to go :+1: 

However, It feels sort of weird that the `user_serializer` actually provides more information than the `authenticated_user_serializer`.

**Comment by joshsmith** [comment]
Ah, good catch! I think those are supposed to reversed, actually.

**Comment by joshsmith** [comment]
No, these can't be reversed. I think I've changed my mind and we should just remove this extra serializer altogether.

**Comment by joshsmith** [comment]
If we're going to hide certain attributes, like I want to do in #243, then we should be doing that all in the same serializer. These things might get pretty granular, so we may as well have a single point of failure for it.

**Comment by begedin** [comment]
:+1:  Looks good to me. I'm thinking, if we need to diverge, we re-add the separation.

Overall, I think responses should mostly only differentiate in includes, not fields or relationships, unless there's a specific need for some sort of optimization

**Comment by joshsmith** [comment]
Right, like there is a need for that optimization in `PostUserMentionsSerializer`, which does not need the entire `Post` serialized with all its includes.

**Pull request merged**
