### PR TITLE
Add newrelic_rpm to gems and configure

### LINKED ISSUE #300: Add New Relic

### PR DESCRIPTION
**Pull request by christopherstyles**
The New Relic [addon](https://elements.heroku.com/addons/newrelic) has been provisioned for the Heroku app, and a `NEW_RELIC_LICENSE_KEY` environment variable added to the configuration. 

New configuration for the app resides in `config/newrelic.yml`.

Resolves #300

### CODE REVIEW

**Comment by joshsmith** [comment]
@christopherstyles has it been provisioned for `code-corps-staging` only or also the production app?

**Comment by joshsmith** [comment]
👍 🐑 🇮🇹

**Comment by christopherstyles** [comment]
@JoshSmith Oh that’s right – mind adding me to the staging app so I can set it up there as well?

**Comment by joshsmith** [comment]
@christopherstyles sure, did you want to add something else to this config then?

**Comment by christopherstyles** [comment]
@JoshSmith No need to add anything else, so long as the `RAILS_ENV` on the staging app is set to `production`. It’ll use the same environment var.

**Comment by joshsmith** [comment]
@christopherstyles it is, just wasn't sure if it would be confusing which New Relic dashboard we're looking at (with naming). But probably doesn't matter all that much.

**Comment by christopherstyles** [comment]
@JoshSmith Okay, gtg on staging now. Since there is no `staging` environment, it can’t be easily changed from the `newrelic.yml`. However, you should be able to change the name of the app from the “Account Settings” in the New Relic dashboard (you’ll need to, as only the app owner can do that).

**Comment by joshsmith** [comment]
@christopherstyles awesome, thanks! 👍

**Pull request merged**
