### PR TITLE
Skills and categories

### LINKED ISSUE #6: Add skills with categories
We want a `Skill` model that includes a `title:string` and a `category`. For example, `Ruby` is in the `Development` category.

### PR DESCRIPTION
**Pull request by begedin**
Closes #6, #7, #8
# Implemented behavior
- A skill has a `title` (required), a`description` (not required) and a `category` (required)
- A category has a `title` (required)
- A `user_skill` has a `user` and a `skill` (both required) and validates that the (`user_id`,`skill_id`) pairs are unique, so we can't create a duplicate
- We have an endpoint for creating `user_skills`
  - It sets the `user` of the `user_skill` to the `current_user` automatically. There is currently no way to assign it manually. We can do it in another PR if we need that feature - #58
  - It requires the `skill` of the `user_skill` to be set to an already existing skill. It cannot create a new one through the request at the moment. If we need that behavior, we can implement it separately - #57 
- We have an endpoint for deleting 'user_skills'
  - It requires the user of the skill to be the current_user. If we want the admin to do it for other users, we can do a separate PR - #58
  - It deletes the `user_skill` only. It doesn't touch the `user` or the `skill`.
- There is no PUT/PATCH endpoint, since there is nothing to edit other than the relationships
# TODO
- [x] Rename `Category` to `SkillCategory`

### CODE REVIEW

**Comment by begedin** [comment]
@JoshSmith This is mergeable, except for the question of the PUT/PATCH endpoint. I've marked the related issue #8 with a question label.

**Comment by joshsmith** [comment]
Do you think `Category` should be a `SkillCategory`?

**Comment by begedin** [comment]
Might be a good idea, depending on what else we might have eventually. It's more descriptive in any case.

**Comment by begedin** [comment]
@JoshSmith Performed the rename. Is this good to go otherwise?

**Pull request merged**
