### PR TITLE
Add more coalescing

### LINKED ISSUE #343: Enable coalesced find requests for GET requests on various endpoints
What I think we need
- [x] Organization memberships - #344
- [x] Organizations - #345
- [x] Users - awaiting review in #347
- [x] User skills - awaiting review in #341
- [x] User categories
- [x] Skills
- [x] Comments
- [x] Posts

Others would make sense, but I think these are higher priority. Feel free to add to this description, though.

Also, I'm expecting duplicate code here, so might be a good idea to refactor into a concern once we have all the individual PRs merged.

### PR DESCRIPTION
**Pull request by joshsmith**
Closes #343.

### CODE REVIEW

**Comment by begedin** [comment]
@JoshSmith I see you commented out includes on `PostsController#show`. Is that permanent? I fixed the tests to reflect this.

**Comment by joshsmith** [comment]
Updated and should be ready for review.

**Comment by begedin** [comment]
Looks good to me, but I wrote part of it, so I'm not sure I'm enough for review.

**Comment by joshsmith** [comment]
Good enough for now. If @christopherstyles wants to give thoughts after merge in case we need to fix something, we can open new issue then. Too time-sensitive, though.

**Pull request merged**
