### PR TITLE
Create posts comments api

### LINKED ISSUE #21: Add endpoint for creating a post
We need to `POST` to create a `Post`.

### PR DESCRIPTION
**Pull request by begedin**
Will close #21, #24 when merged
# Description

This is still a work in progress. Since I made validation and access errors follow the JSON API in #49, I decided to add "pending" statements to specs in this one until #49 is merged. Otherwise, I would have to do repeat work as well as additional work resolving conflicts once both are ready for merge.

Outside of that, here's what we have:
- We can GET individual and multiple posts, no pagination yet, since there's a separate issue for that
- We can create posts
  - `title` is required
  - `body` is not required
  - `type` was changed to `post_type`, since `type` is a reserved name
  - `type` is permitted but has a default set to "task"
  - `status` is permitted as a parameter, but is ignored. Instead, we set it to "open" by default.
  - `project_id` is required as a parameter
  - `user_id` is required as a parameter, but is auto-set to the current user
  - Anyone who is signed in can create posts - this is a very basic ability and needs to be improved on, in a separate issue, I think - #50
- We can't get individual or multiple comments for now. I'm thinking they can be included with posts.
  - Once we have paging, we should be able to filter comments by post_id and then retrieve individual pages.
- We can create comments
  - `body` is required
  - `post_id` is required
  - `user_id` is required, but is auto-set to the current user

### CODE REVIEW

**Comment by joshsmith** [comment]
#49 is merged.

**Comment by begedin** [comment]
Since #49 is merged, and pending specs are fixed, this should be mergeable as well.

**Comment by joshsmith** [comment]
I'm not sure I understand why this isn't passing, but maybe you can fix it. Good to merge, though I would consider making `body` in `Post` required.

**Comment by JoshSmith** [comment]
simulator screen shot nov 24 2015 6 07 53 pm

**Comment by begedin** [comment]
@JoshSmith Regarding making the body of post required, I was going with the same approach as github, where you can create an issue with just a title, no body.

**Comment by begedin** [comment]
@JoshSmith If you could quickly review this, now that the tests pass, I could merge it (or add the post body requirement, then merge), since it's blocking #60

**Comment by joshsmith** [comment]
Looks good to me, but I definitely think a body is a good idea. I don't like Github's approach personally. Leads to over-long titles for things.

**Pull request merged**
