### PR TITLE
Add ProjectSkill

### LINKED ISSUE #271: Add ProjectSkill model
We need to add a `ProjectSkill` model and associated behavior.

### PR DESCRIPTION
**Pull request by joshsmith**
Closes #271.
- [x] Add `ProjectSkill` model and specs
- [x] Add `ProjectSkillPolicy` and specs
- [x] Add to `Project` as `has_many`
- [x] Add to `ProjectSerializer` and specs
- [x] Add `ProjectSkillSerializer` and specs
- [x] Add project skill API specs, controller, routes, etc.

### CODE REVIEW

**Comment by begedin** [comment]
Looks good 👍 

I like that we aren't exposing "project_skills" with the project serializer, only "skills". We don't really need the weak entity client side and it simplifies things, probably. 

We should keep that in mind with other similar cases.

**Comment by joshsmith** [comment]
@begedin actually I do think we might need the weak entity client-side when it comes to creating/deleting the project skill. We ended up needing it in the case of users categories and users skills.

**Comment by begedin** [comment]
@JoshSmith Either way, it's something to keep in mind. It's possible that sometimes, we wont.

**Comment by joshsmith** [comment]
Yes, agreed.

**Pull request merged**
