### PR TITLE
Add team projects and specs

### LINKED ISSUE #144: Create team projects
There should be a `TeamProject` model and `Team` should `has_many :team_projects` and `has_many projects, through: :team_projects`.

A `TeamProject` should additionally have an `enum` of role permissions similar to `OrganizationMembership`.

### PR DESCRIPTION
**Pull request by joshsmith**
Closes #144

### CODE REVIEW

**Comment by scarfdestroyer** [comment]
Looks good to me.

**Comment by joshsmith** [comment]
This PR does not actually make use of the `TeamProject`, which needs resolved in #146. We'll merge this first and tackle separately.

There are also some refactorings of `PostPolicy` since this policy had some issues, and to make it clearer for us to refactor _again_ when teams are brought into the mix.

**Comment by joshsmith** [comment]
@scarfdestroyer did refactoring of `PostPolicy` make sense?

**Comment by scarfdestroyer** [comment]
@JoshSmith  yeah and having each bit of logic itemized with comments so we know what it's purpose is, is good for any future changes.

**Pull request merged**
