### PR TITLE
Skip relevant tests if the missing the config

### PR DESCRIPTION
**Pull request by justinabrahms**
This allows people to have passing tests after first installation.

### CODE REVIEW

**Comment by justinabrahms** [comment]
It'd also be really rad if I could run this linting locally, because getting 20+ emails on PR opening is frustrating.

**Comment by joshsmith** [comment]
@justinabrahms I agree. I think as nice as Hound is for helping to enforce some conventions, it's kind of a PITA. @begedin has been grumbling about it for awhile. I think we just need to pull it altogether.

**Comment by begedin** [comment]
We could still be using hound, but we should either set it up to user our own config, or we should switch to using hound's config.

I'm not sure we gain much from it, though. Local linting should suffice, if we take it seriously enough.

In any case, we need to agree on a common set of styles.

**Comment by justinabrahms** [comment]
Simply having something I could run locally would be good for what I
wanted.

On Monday, January 11, 2016, Nikola Begedin notifications@github.com
wrote:

> We could still be using hound, but we should either set it up to user our
> own config, or we should switch to using hound's config.
> 
> I'm not sure we gain much from it, though. Local linting should suffice,
> if we take it seriously enough.
> 
> In any case, we need to agree on a common set of styles.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/code-corps/code-corps-api/pull/153#issuecomment-170451288
> .

## 

Sent via mobile phone.

**Comment by joshsmith** [comment]
After some discussion, we've opted to close this in favor of finding ways to remove ENV reliance.

**Pull request closed without merging**
